// <auto-generated />
using System;
using MelissaWare.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MelissaWare.Context.Migrations
{
    [DbContext(typeof(MelissaWareDBContext))]
    [Migration("20200614212922_FirstSetup")]
    partial class FirstSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MelissaWare.Entities.Classroom", b =>
                {
                    b.Property<int>("ClassroomKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassroomMaxStudents")
                        .HasColumnType("int");

                    b.Property<string>("ClassroomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherKey")
                        .HasColumnType("int");

                    b.HasKey("ClassroomKey");

                    b.HasIndex("TeacherKey");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("MelissaWare.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherKey");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("MelissaWare.Entities.Classroom", b =>
                {
                    b.HasOne("MelissaWare.Entities.Teacher", "Teacher")
                        .WithMany("Classrooms")
                        .HasForeignKey("TeacherKey");
                });
#pragma warning restore 612, 618
        }
    }
}
