// <auto-generated />
using System;
using MelissaWare.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MelissaWare.Context.Migrations
{
    [DbContext(typeof(MelissaWareDBContext))]
    partial class MelissaWareDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MelissaWare.Entities.Classroom", b =>
                {
                    b.Property<int>("ClassroomKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassroomMaxStudents")
                        .HasColumnType("int");

                    b.Property<string>("ClassroomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherKey")
                        .HasColumnType("int");

                    b.HasKey("ClassroomKey");

                    b.HasIndex("TeacherKey");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("MelissaWare.Entities.Student", b =>
                {
                    b.Property<int>("StudentKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClassroomKey")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentKey");

                    b.HasIndex("ClassroomKey");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MelissaWare.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeacherName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherKey");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("MelissaWare.Entities.Classroom", b =>
                {
                    b.HasOne("MelissaWare.Entities.Teacher", "Teacher")
                        .WithMany("Classrooms")
                        .HasForeignKey("TeacherKey");
                });

            modelBuilder.Entity("MelissaWare.Entities.Student", b =>
                {
                    b.HasOne("MelissaWare.Entities.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomKey");
                });
#pragma warning restore 612, 618
        }
    }
}
